services:
  task-microservice:
    image: task-microservice:latest
    container_name: task-microservice
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/task_microservice
      - DB_USERNAME=developer
      - DB_PASSWORD=123456
    ports:
      - 8080:8080
  db:
    image: postgres:16
    container_name: microservicedb
    environment:
      - POSTGRES_DB=task_microservice
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=developer
    ports:
      - 8000:5432